version: '3.8'

services:
  mongo:
    image: mongo
    restart: always
    env_file:
      - ./docker/mongo/.mongo-env
    volumes:
      - ./docker/mongo/datasets:/datasets
      - ./docker/mongo/db_init.sh:/docker-entrypoint-initdb.d/db_init.sh

  mongo-express:
    image: mongo-express
    depends_on: 
      - mongo
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  
  express-solita:
    image: express-solita
    container_name: express-solita
    depends_on: 
      - mongo
    env_file:
      - ./docker/mongo/.mongo-env
    build: 
      context: ./
      dockerfile: ./docker/Dockerfile.prod
    ports:
      - 5000:3000
    # volumes:
    #   - ./server:/app
    #   - /app/node_modules # anonymous volume (not bound to host)